error: can't copy 'resource/py_drive': doesn't exist or not a regular file
